### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by danielroe** [Hebilicious/vue-query-nuxt#4]
This looks great! A few suggestions:

1. it might be worth using `addTemplate` rather than the current custom `writeFile` implementation. It supports `write: true` option if you need it written to disk, and it will create it within `.nuxt` by default.
2. The same is true for your augmentation of `types/plugins.d.ts`. You can write a custom type declaration file with `addTemplate` and then use the `prepare:types` hook to add a reference to this declaration file to the Nuxt types.
3. Instead of manually being in charge of re-writing the file when config changes you can use the `updateTemplates` utility provided by kit.

**Comment by Hebilicious** [comment]
> This looks great! A few suggestions:
> 
> 1. it might be worth using `addTemplate` rather than the current custom `writeFile` implementation. It supports `write: true` option if you need it written to disk, and it will create it within `.nuxt` by default.
> 2. The same is true for your augmentation of `types/plugins.d.ts`. You can write a custom type declaration file with `addTemplate` and then use the `prepare:types` hook to add a reference to this declaration file to the Nuxt types.
> 3. Instead of manually being in charge of re-writing the file when config changes you can use the `updateTemplates` utility provided by kit.

Thank you for reviewing my module !


The reason I did handle the file writing logic manually was because I couldn't get `updateTemplates` to behave like a fresh fsp.writeFile, and calling `addTemplates` again doesn't rewrite the file either :/

Maybe we could add something like this in Kit ? `addTemplate({ filename, write: true, getContents, overwrite : true })` so that calling addTemplate again overwrite the previous file with a fresh getContents.

Regarding the types, that's what I was doing initially, but somehow the types declared in another file were not registering correctly (in my case I want to extend the NuxtApp type). The only was it worked was to add these types directly in plugin.d.ts, but now it looks like it somehow doesn't work anymore (even without the module/with manual types, it appears I can't extend the NuxtApp interface). I must be doing something wrong ...

**Comment by Hebilicious** [comment]
Actually @danielroe I was able to fix the types issue here https://github.com/Hebilicious/vue-query-nuxt/commit/8e72f912bdbf261ebe9533e268c97ac58975a6ce 

Should I open a PR for this @nuxt/kit feature ? That would be quite neat.

**Comment by danielroe** [comment]
I would consider it a bug if `updateTemplates` doesn't update the file that's written to disk.

**Comment by Hebilicious** [comment]
https://github.com/nuxt/nuxt/pull/21331 I've opened this @danielroe
